baseurl: https://cours-immunologie.netlify.app/
title: Acceuil
theme: hugo-theme-console
languageCode: en-us
googleAnalytics: G-VZB1ER63K6
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: A propos/
      url: about/
    - name: Cours/
      url: posts/
    - name: Grade-QCM/
      url: photos/
  titleCutting: yes
